### PR TITLE
Problem: chain-main can't be built for windows (fix #406)

### LINKED ISSUE #406: Problem: chain-main can't be built for windows
```
 failed after 216.97s error=failed to build for windows_amd64: # github.com/crypto-org-chain/chain-main/v1/cmd/chain-maind/app
111
cmd/chain-maind/app/app.go:160:10: undefined: renameio.WriteFile
```

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: use ioutil.WriteFile,
file atomicity is done via file level.

### CODE REVIEW

File: cmd/chain-maind/app/app.go [hunk 1]
```diff
@@ -38,7 +39,6 @@ import (
 	"github.com/crypto-org-chain/chain-main/v1/app/params"
 	"github.com/crypto-org-chain/chain-main/v1/config"
 	chainmaincli "github.com/crypto-org-chain/chain-main/v1/x/chainmain/client/cli"
-	"github.com/google/renameio"
```
Comment (tomtau) [inline cmd/chain-maind/app/app.go:41]: maybe also remove the dependency from go.mod?

Comment (leejw51crypto) [reply cmd/chain-maind/app/app.go:41]: ok, i'll check

**Comment by tomtau** [comment]
vendorSha256 may need to be updated for integration tests: https://github.com/crypto-org-chain/chain-main/pull/409/checks?check_run_id=2074911879 ?

**Comment by JayT106** [comment]
So the root cause was the `renameio` implementation not compatible with the windows system.
And the CI doesn't have the binary build check across platforms?

**Comment by tomtau** [comment]
> So the root cause was the `renameio` implementation not compatible with the windows system.
> And the CI doesn't have the binary build check across platforms?

That's correct -- CI only had Windows build for binary releases, so that's where this got caught: https://github.com/crypto-org-chain/chain-main/runs/2063584065?check_suite_focus=true#step:4:111

I think for this PR, it'll also be good to extend the existing CI workflow ( https://github.com/crypto-org-chain/chain-main/blob/master/.github/workflows/build.yml ) or add a new one (as that "build" workflow has many other steps that one doesn't need to worry about for simple "does it build on anything else than Linux?" check)

It should be possible with
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by tomtau** [comment]
conflict with the latest master

**Comment by leejw51crypto** [comment]
rebased

**Comment by leejw51crypto** [comment]
add windows, mac build step

**Comment by tomtau** [comment]
it seems the Windows "build" doesn't get executed: https://github.com/crypto-org-chain/chain-main/pull/409/checks?check_run_id=2084141603#step:9:3 it'll just checkout the code, but won't try to build it

**Comment by tomtau** [comment]
@allthatjazzleo

**Comment by leejw51crypto** [comment]
i'll check windows, mac build

**Comment by tomtau** [comment]
builds now, but fails with:
```
# github.com/crypto-org-chain/chain-main/v1/cmd/chain-maind
97
C:\hostedtoolcache\windows\go\1.15.5\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
98
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Error: export ordinal too large: 69810
99
collect2.exe: error: ld returned 1 exit status
100
```

**Comment by leejw51crypto** [comment]
that's golang issue for windows

applied this flag `buildmode`
 build  -buildmode=exe -mod=readonly $(BUILD_FLAGS) $(BUILD_TAGS) -o $(BUILDDIR)/chain-maind ./cmd/chain-maind

File: Makefile [hunk 2]
```diff
@@ -45,6 +45,11 @@ install: check-network go.sum
 
 build: check-network go.sum
 		go build -mod=readonly $(BUILD_FLAGS) $(BUILD_TAGS) -o $(BUILDDIR)/chain-maind ./cmd/chain-maind
+
+buildwindows: check-network go.sum
+		go build  -buildmode=exe -mod=readonly $(BUILD_FLAGS) $(BUILD_TAGS) -o $(BUILDDIR)/chain-maind ./cmd/chain-maind
```
Comment (allthatjazzleo) [inline Makefile:50]: an extra space there after `go build`

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -73,8 +78,14 @@ jobs:
         run: |
           echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
       - name: build
+        if: startsWith(matrix.os, 'ubuntu')
         run: make build
-        if: "env.GIT_DIFF != '' || github.event_name == 'issue_comment'"
```
Comment (tomtau) [inline .github/workflows/build.yml:77]: if this condition isn't there, it may break the "/runsim" simulation workflow -- @allthatjazzleo may comment?

perhaps for windows/Mac -- instead of changing "build.yml", create a separate workflow ?

Comment (allthatjazzleo) [reply .github/workflows/build.yml:77]: This line shall not break "/runsim", it was to make sure the workflow will run only when there are some changes in `.go .mod .sum` file.
But since `technote-space/get-diff-action` step will empty result when event is `issue_comment`. I needed to put the second condition for event triggered by `/runsim` manually.

File: cmd/chain-maind/app/app.go [hunk 4]
```diff
@@ -157,7 +157,7 @@ func initRootCmd(rootCmd *cobra.Command, encodingConfig params.EncodingConfig) {
 			return err
 		}
 
-		return renameio.WriteFile(cleanedPath, bz, 0600)
+		return ioutil.WriteFile(cleanedPath, bz, 0600)
```
Comment (yihuang) [inline cmd/chain-maind/app/app.go:160]: We need to reopen this issue then. https://github.com/crypto-org-chain/chain-main/issues/398

Comment (tomtau) [reply cmd/chain-maind/app/app.go:160]: seems not possible on Windows: https://github.com/google/renameio#windows-support ?

Comment (tomtau) [reply cmd/chain-maind/app/app.go:160]: or keep using renameio, just pin the dependency to be before https://github.com/google/renameio/commit/8b2b09a2cfe0f9be5e3b41bdf85c0baf422c0f6f knowing it's not reliable on Windows?

Comment (yihuang) [reply cmd/chain-maind/app/app.go:160]: is it possible to conditional compile?

Comment (tomtau) [reply cmd/chain-maind/app/app.go:160]: it should be: https://golang.org/cmd/go/#hdr-Build_constraints

so I guess one other option is to separate it out and `// +build !windows` on "app.go"-subset and have some Windows "app.go"-subset ?

Comment (tomtau) [reply cmd/chain-maind/app/app.go:160]: @leejw51crypto

File: Makefile (hunk 2 above)
Comment (leejw51crypto) [reply Makefile:50]: ok, i'll modify

File: cmd/chain-maind/app/app.go (hunk 4 above)
Comment (leejw51crypto) [reply cmd/chain-maind/app/app.go:160]: ok, i'll apply conditional compile

**Comment by leejw51crypto** [comment]
working now

**Comment by leejw51crypto** [comment]
renameio for darwin, linux
ioutil for window

rebased

File: go.mod [hunk 5]
```diff
@@ -8,7 +8,7 @@ require (
 	github.com/cosmos/ledger-go v0.9.2 // indirect
 	github.com/gogo/protobuf v1.3.3
 	github.com/golang/protobuf v1.4.3
-	github.com/google/renameio v1.0.0
+	github.com/google/renameio v0.1.0
```
Comment (tomtau) [inline go.mod:11]: keep 1.0.0?

**Review by tomtau — CHANGES_REQUESTED** [review]
I guess two options:
1. have just one "app.go" and use the old renameio
2. have two "app.go" and use the latest renameio -- just add build tags on the subset

for the second one, it'll be good to extract out the common functionality

File: go.mod (hunk 5 above)
Comment (leejw51crypto) [reply go.mod:11]: ok, i will go for option2, change version , too.

File: .github/workflows/build.yml (hunk 3 above)
Comment (leejw51crypto) [reply .github/workflows/build.yml:77]: restored back , if condtions

**Review by tomtau — APPROVED** [review]
